### ISSUE TITLE
Cannot disconnect or change server

### ISSUE THREAD

**Issue by dobrys** [AdguardTeam/AdGuardVPNForWindows#242]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:v1.2.497.0
  - 
- **VPN mode:Local VPN
  - 
- **Operating system and version:Windows 10 Pro
  - 
- **Other network-level software:AdGuard (paid),Malwarebytes,Windows defender
  - 

### Expected Behavior

When click on disconnect ,I'm expecting VPN to be disconnected

### Actual Behavior

It,s stay forever in disconnecting state

### Screenshots

<details><summary>Screenshot:
![image](https://user-images.githubusercontent.com/839961/161373354-00aa10c9-7073-4e46-897e-448875a7614c.png)
</summary>

</details>

### Additional Information

from client_xxx.log:

INFO, AdGuardVpn, 4, 02.04.2022 10:44:28.196, Reload VpnConnectionState
INFO, AdGuardVpn, 4, 02.04.2022 10:44:28.217, VpnConnectionState: connected
INFO, AdGuardVpn, 1, 02.04.2022 10:44:28.258, Is Operation system theme light? : True
WARNING, AdGuardVpn, 1, 02.04.2022 10:45:46.594, Cannot find method onclosewindow among the existing backend methods
INFO, AdGuardVpn, 1, 02.04.2022 10:48:19.495, On RestoreMainWindow
INFO, AdGuardVpn, 35, 02.04.2022 10:51:22.276, Initializing default proxy
INFO, AdGuardVpn, 35, 02.04.2022 10:51:22.299, Default proxy has been initialized.
INFO, AdGuardVpn, 17, 02.04.2022 10:54:27.840, ApplicationApiClient - <VpnConnect>b__0: Reconnecting after timeout
ERROR, AdGuardVpn, 17, 02.04.2022 11:04:27.845, ApplicationApiClient - <VpnConnect>b__0: max reconnect times (1) has been exceeded
WARNING, AdGuardVpn, 17, 02.04.2022 11:04:27.846, ApplicationApiClient: Error while calling service method <VpnConnect>b__0
WARNING, AdGuardVpn, 17, 02.04.2022 11:04:27.862, Error while processing task: System.TimeoutException: This request operation sent to net.pipe://127.0.0.1/AdguardVpnApiEndpoint did not receive a reply within the configured timeout (00:10:00).  The time allotted to this operation may have been a portion of a longer timeout.  This may be because the service is still processing the operation or because the service was unable to send a reply message.  Please consider increasing the operation timeout (by casting the channel/proxy to IContextChannel and setting the OperationTimeout property) and ensure that the service is able to connect to the client.
Source: mscorlib
Stack trace: 
Server stack trace: 
   at System.ServiceModel.Dispatcher.DuplexChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at AdGuardVpn.Ipc.Contract.IUiApplicationApiFacade.VpnConnect(String locationId)
   at AdGuardVpn.Ipc.Client.UiApplicationApiClient.<>c__DisplayClass18_0.<VpnConnect>b__0(IUiApplicationApi api)
   at AdGuardVpn.Ipc.Client.BasicApplicationApiClient`1.ExecuteServiceMethodOnce(UseServiceDelegate codeBlock)
   at AdGuardVpn.Ipc.Client.BasicApplicationApiClient`1.ExecuteServiceMethod(UseServiceDelegate codeBlock)
   at AdGuardVpn.Ipc.Client.BasicApplicationApiClient`1.CallServiceMethod(UseServiceDelegate codeBlock)
   at AdGuardVpn.Ipc.Client.UiApplicationApiClient.VpnConnect(String locationId)
   at Wnt8lZvFprJtroKdqd.WSprb3ASX(Object , String , Wnt8lZvFprJtroKdqd )
   at AdGuardVpn.UI.Service.Impl.ClientVpnConnectionService.Connect(String locationId)
   at AdGuardVpn.UI.Backend.BackendApi.q4vWUA1mFsMiawvCTv.ABtNokX9tZI6CZfx7yu(Object , Object )
   at AdGuardVpn.UI.Backend.BackendApi.q4vWUA1mFsMiawvCTv.Qq76XLDWqU()
   at AdGuard.Utils.Threading.FastThreadPoolWorker.Ghb9GaWEVpFnb7ywuve(Object )
   at AdGuard.Utils.Threading.FastThreadPoolWorker.kVp3C5ng2K()

**Comment by northis** [comment]
@dobrys Please, send your logs to devteam@adguard.com.
How to get the logs:
https://uploads.adguard.com/north4zni8.png

**Comment by dobrys** [comment]
sent







 >-------- Оригинално писмо --------

 >От: Mikhail Berdnikov ***@***.***

 >Относно: Re: [AdguardTeam/AdGuardVPNForWindows] Cannot disconnect or change
 server (Issue #242)

**Comment by Aydinv13** [comment]
Closed as a duplicate 
https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/175

**Comment by dobrys** [comment]
Great !
and what I shell do to use it normally ?

**Comment by northis** [comment]
@dobrys Looks like there are some problems in your system:
```
System.ComponentModel.Win32Exception: This service cannot be started in Safe Mode
...
System.ComponentModel.Win32Exception: A system shutdown is in progress
```
Have you tried to reboot your PC?

**Comment by dobrys** [comment]
sure, a lot 
no difference!
